### ISSUE TITLE
Error searching for subtitles

### ISSUE THREAD

**Issue by onoakino** [opensubtitlesdev/service.subtitles.opensubtitles-com#19]
Running this add-on on Kodi 20.1.0. 
When searching for subtitles, it keeps on throwing "Error searching for subtitles". It doesn't matter if I use a newly created and verified account on subtitles.com, or if I use my imported opensubtitles.org credentials. I'm not a VIP member, but free users should have 10 free subtitle downloads per day, and yet I haven't been able to download one.

**Comment by opensubtitlesdev** [comment]
the problem can come from multiple reasons, can you put your setup in debug mode and send us the log ? please try to run a few titles so theres a few searches or download attempts to look at.

then you can contact us to open a ticket. https://www.opensubtitles.com/en/contact/
