### ISSUE TITLE
Subtitle filename missing language for Portuguese

### ISSUE THREAD

**Issue by lightglitch** [opensubtitlesdev/service.subtitles.opensubtitles-com#22]
When you download a Portuguese subtitle the naming of the file is incorrect, the language is not added to the file name.

It shows
```
Rocketman.2019.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT..srt
```
instead of 
```
Rocketman.2019.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT.pt.srt
```

**Comment by lightglitch** [comment]
Just to add more information, this only happens with pt subtitles, english subtitles the suffix is added correctly.

**Comment by opensubtitlesdev** [comment]
sorry for the late reply... yeah I noticed, couldn't find a fix yet but we have a new developer who offered to help us with this

**Comment by nilskp** [comment]
For Brazilian Portuguese, the name should be:
```
Rocketman.2019.1080p.BluRay.x264.TrueHD.7.1.Atmos-FGT.pb.srt
```

**Comment by opensubtitlesdev** [comment]
We surely know what name the file should get, but it's several month of searching to figure out what part of the plugin sends back the language to the part that handles file downloads in Kodi.

We are totally lost on the topic, we had 2 python developpers who offered to help, didn't understand either and gave up .

if a python developer reads this, can understand what is going on in 
https://github.com/opensubtitlesdev/service.subtitles.opensubtitles-com/blob/master/resources/lib/data_collector.py

and is willing to give us a hand, he'll get eternal gratitude and lifetime VIP on our platforms.

**Comment by JimmyS83** [comment]
> stead of

I review code, and tryin thinking out of the box, you can create your own filename, instead of using uuid.

in `subtitle_downloader.py`

**remove**
import uuid

**add** 
import xbmc

**within download(self):**
**replace**
`subtitle_path = os.path.join(__temp__, f"{str(uuid.uuid4())}.{self.sub_format}")`

with
```
try:    # kodi > k19
    dir_path = xbmcvfs.translatePath('special://temp/oss')       
except: # kodi < k19
    dir_path = xbmc.translatePath('special://temp/oss')

# Kodi lang-code difference vs OS.com API langcodes return
if self.params["language"].lower() == 'pt-pt': self.params["language"] = 'pt'
elif self.params["language"].lower() == 'pt-pb': self.params["language"] = 'pb'

if xbmcvfs.exists(dir_path):    # lets clean files from last usage
    dirs, files = xbmcvfs.listdir(dir_path)
    for file in files:
        xbmcvfs.delete(os.path.join(dir_path, file))
        
if not xbmcvfs.exists(dir_path):  # lets create custom OSS sub directory if not exists
    xbmcvfs.mkdir(dir_path)

subtitle_path = os.path.join(dir_path, "{0}.{1}.{2}".format('TempSubtitle', self.params["language"], self.sub_format))
```


**within list_subtitles(self):**
**replace**
`url = f"plugin://{__scriptid__}/?action=download&id={attributes['files'][0]['file_id']}"`
with
`url = f"plugin://{__scriptid__}/?action=download&id={attributes['files'][0]['file_id']}&language={attributes['language']}"`

**Comment by opensubtitlesdev** [comment]
finally fixed and merged, thanks to [JimmyS83](https://github.com/JimmyS83) !
