### ISSUE TITLE
getting: error searching for subtitles

### ISSUE THREAD

**Issue by herbie4** [opensubtitlesdev/service.subtitles.opensubtitles-com#23]
Hi, 
I added my credentials but I am getting the error message: error searching for subtitles. 
Any ideas what to do to fix this. Using the 1.0.2 version of the addon in kodi.

**Comment by herbie4** [comment]
Now updated to this repo version 1.0.4 and it is working. Just wondering why this version is not in de kodi addon repo.

**Comment by opensubtitlesdev** [comment]
maybe you had updates disabled somehow ?  version 1.0.4 was published 3 weeks ago in the matrix branch https://github.com/xbmc/repo-scripts/tree/matrix

**Comment by herbie4** [comment]
> maybe you had updates disabled somehow ? version 1.0.4 was published 3 weeks ago in the matrix branch https://github.com/xbmc/repo-scripts/tree/matrix

Updates is on in Kodi. I uninstalled 1.0.2 version because of error and installed from kodi addons list and got the 1.0.2 version again (with error). After that I downloaded it from here and installed 1.0.4. Now it is working. Great work.
