### ISSUE TITLE
Plugin crashes Kodi on Ubuntu 24.04

### ISSUE THREAD

**Issue by mprotic** [opensubtitlesdev/service.subtitles.opensubtitles-com#28]
Kodi 20.5, Ubuntu 24.04, searching for subtitles works, but when I select one subtitle the plugin crashes Kodi. 
Same behaviour on multiple computers with ubuntu 24.04. When started from terminal Kodi gives following error when subtitle is selected (on crash):

Fatal Python error: PyImport_AppendInittab: PyImport_AppendInittab() may not be called after Py_Initialize()
Python runtime state: initialized

Quick search for this error message on internet suggests that is seems like a problem with python version, Ubuntu being shipped with python 3.12.3

**Comment by mprotic** [comment]
OK, this seems to be Ubuntu issue, Ubuntu distributes old Kodi version 20.5 which seems to be incompatible with python 3.12.

Workaround: install Kodi 21.1 from flatpak or another source and everything works again.

Can close this isssue.

**Comment by opensubtitlesdev** [comment]
ok, thank you for keeping us updated !
