### ISSUE TITLE
I get the error: "Error getting the subtitle", whenever I select any subtitle. 

### ISSUE THREAD

**Issue by tfouto** [opensubtitlesdev/service.subtitles.opensubtitles-com#31]

**Comment by tfouto** [comment]
I get the error: "Error getting the subtitle", whenever I select any subtitle. Then it chooses another completly random subtitle.

Log: https://pastebin.com/rdDXRd5c

**Comment by tfouto** [comment]
Started worked after an unistall and clean install. Altough I had done the same yesterday and didn't work. Whatever.

**Comment by opensubtitlesdev** [comment]
sorry for the troubles, that was all just some configuration errors on our proxy...
